### ISSUE TITLE
Thanks and a small tip

### ISSUE THREAD

**Issue by dobbelina** [DominiqueMakowski/DominiqueMakowski.github.io#2]
@DominiqueMakowski 
Thanks for the article here:[How to sync two folders in two separate GitHub repositories](https://realitybending.github.io/post/2021-10-31-sync_two_repos/)
This helped me a lot.
A small tip is, if you don't want that static commit message but instead the actual message that is more informative, then change this:
 `commit_message: "AUTO: Copying posts from Dom's to REBEL's website"`
To this:
`commit_message: ${{ github.event.head_commit.message }}`

**Comment by DominiqueMakowski** [comment]
Thanks @dobbelina I added that in the [post](https://dominiquemakowski.github.io/post/2021-10-31-sync_two_repos/) :)
